### ISSUE TITLE
What version of Stanford Parser did you use in ADW project?

### ISSUE THREAD

**Issue by canadianvpk** [pilehvar/ADW#11]
Hi - I am using your **adw.v1.0.jar** file in my project to compute the similarity score. Already in my work I used Stanford parser version 3.5.2. I guess in your jar file you bundled up with some version of stanford parser as well. Can you please let me know that version ? It will help me to fix the bugs I get because of version clash. Kind request and thanks!.

**Comment by canadianvpk** [comment]
- [ ] 

- [ ]

**Comment by canadianvpk** [comment]
This is the error message I get, just in case you want to see the error:

`!!!***....Project begins.......***!!!
Loading parser from serialized file src/main/java/models/englishPCFG.ser.gz ... Exception in thread "main" java.lang.NoSuchMethodError: edu.stanford.nlp.util.Generics.newHashMap()Ljava/util/Map;
    at edu.stanford.nlp.parser.lexparser.BinaryGrammar.init(BinaryGrammar.java:223)
    at edu.stanford.nlp.parser.lexparser.BinaryGrammar.readObject(BinaryGrammar.java:211)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(LexicalizedParser.java:195)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParser.getParserFromSerializedFile(LexicalizedParser.java:604)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParser.getParserFromFile(LexicalizedParser.java:398)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(LexicalizedParser.java:181)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(LexicalizedParser.java:160)
    at com.javaYu.userStudyNLP.mainClass3.main(mainClass3.java:74)
`

**Comment by minafarid** [comment]
Seconded, please advise on the version being used. Thanks

**Comment by pilehvar** [comment]
stanford-parser-2011-05-18.jar
