### ISSUE TITLE
Null Pointer Exception when trying to run.

### ISSUE THREAD

**Issue by Achilles-96** [pilehvar/ADW#13]
Is there any resource I am missing.

Apr 07, 2017 12:11:42 AM it.uniroma1.lcl.adw.ADWConfiguration <init>
INFO: Loading adw.properties FROM /home/raghuram/eclipse/workspace/PEAK/config/adw.properties
Apr 07, 2017 12:11:42 AM it.uniroma1.lcl.jlt.Configuration <init>
INFO: Loading jlt.properties FROM /home/raghuram/eclipse/workspace/PEAK/config/jlt.properties
java.lang.RuntimeException: Cannot init: java.lang.NullPointerException
	at it.uniroma1.lcl.jlt.pipeline.stanford.StanfordPOSTagger.<init>(StanfordPOSTagger.java:39)
	at it.uniroma1.lcl.jlt.pipeline.stanford.StanfordPOSTagger.getInstance(StanfordPOSTagger.java:45)
	at it.uniroma1.lcl.jlt.pipeline.stanford.DataProcessor.processSentence(DataProcessor.java:87)
	at it.uniroma1.lcl.adw.textual.similarity.TextualSimilarity.getStanfordSentence(TextualSimilarity.java:114)
	at it.uniroma1.lcl.adw.textual.similarity.TextualSimilarity.cookSentence(TextualSimilarity.java:252)
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.cookLexicalItem(PairSimilarity.java:119)
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.getSimilarity(PairSimilarity.java:278)
	at it.uniroma1.lcl.adw.ADW.getPairSimilarity(ADW.java:123)
	at model1.step1.step1(step1.java:263)
	at model1.model1.main(model1.java:9)
java.lang.NullPointerException
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.cookLexicalItem(PairSimilarity.java:120)
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.getSimilarity(PairSimilarity.java:278)
	at it.uniroma1.lcl.adw.ADW.getPairSimilarity(ADW.java:123)
	at model1.step1.step1(step1.java:263)
	at model1.model1.main(model1.java:9)
Exception in thread "main" java.lang.NullPointerException
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.getSimilarity(PairSimilarity.java:278)
	at it.uniroma1.lcl.adw.ADW.getPairSimilarity(ADW.java:123)
	at model1.step1.step1(step1.java:263)
	at model1.model1.main(model1.java:9)

**Comment by Achilles-96** [comment]
Also, I am unable to find source for `it.uniroma1.lcl.jlt` . If I find that, I can debug the error myself.

**Comment by saraswat** [comment]
Make sure you do a ```mvn install```. What command line did you use?

**Comment by Achilles-96** [comment]
I am using eclipse.

**Comment by saraswat** [comment]
I am sorry, that does not help. For others to reproduce the problem (and hence help you), you need to communicate (a) did you run `mvn install` (depending on the options installed within Eclipse you could do this within Eclipse), and (b) What script/class did you run, and what arguments did you supply?
