### ISSUE TITLE
Execution gives exception

### ISSUE THREAD

**Issue by cryptexcode** [pilehvar/ADW#6]
I followed the instructions given and tried to run the source in Netbeans. But got these exceptions.

cd /home/ritual/SK/Works/SemEval_Task_3/ADW_tool/ADW-master; JAVA_HOME=/home/ritual/jdk1.8.0_60 /home/ritual/netbeans-8.0.2/java/maven/bin/mvn "-Dexec.args=-classpath %classpath it.uniroma1.lcl.adw.ADW" -Dexec.executable=/home/ritual/jdk1.8.0_60/bin/java -Dexec.classpathScope=runtime org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...

Some problems were encountered while building the effective model for ADW:ADW:jar:0.0.1-SNAPSHOT
'dependencies.dependency.systemPath' for in-project:jlt:jar should not point at files within the project directory, ${basedir}/lib/jlt-2.0.0.jar will be unresolvable by dependent projects @ line 38, column 16

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.

                                                                        
------------------------------------------------------------------------
Building ADW 0.0.1-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ ADW ---
Oct 28, 2015 6:37:34 PM it.uniroma1.lcl.adw.ADWConfiguration <init>
INFO: Loading adw.properties FROM /home/ritual/SK/Works/SemEval_Task_3/ADW_tool/ADW-master/config/adw.properties
Exception in thread "main" java.lang.NoClassDefFoundError: it/uniroma1/lcl/jlt/util/EnglishLemmatizer
	at it.uniroma1.lcl.adw.textual.similarity.TextualSimilarity.<init>(TextualSimilarity.java:73)
	at it.uniroma1.lcl.adw.textual.similarity.TextualSimilarity.getInstance(TextualSimilarity.java:92)
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.cookLexicalItem(PairSimilarity.java:148)
	at it.uniroma1.lcl.adw.textual.similarity.PairSimilarity.getSimilarity(PairSimilarity.java:293)
	at it.uniroma1.lcl.adw.ADW.getPairSimilarity(ADW.java:120)
	at it.uniroma1.lcl.adw.ADW.main(ADW.java:213)
Caused by: java.lang.ClassNotFoundException: it.uniroma1.lcl.jlt.util.EnglishLemmatizer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 0.900s
Finished at: Wed Oct 28 18:37:35 CDT 2015
Final Memory: 8M/479M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project ADW: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by taniakhan18** [comment]
Did you solve this error
